spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jainpooja9810@gmail.com
spring.mail.password=kuft xtae zmgd wimk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#H2 database connection properties
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/email_automation_db
spring.datasource.username=postgres
spring.datasource.password=dataDB26
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect